cloneable_entities:
  - block
  - block_content
  - block_content_type
  - comment
  - comment_type
  - contact_message
  - contact_form
  - editor
  - field_config
  - field_storage_config
  - file
  - filter_format
  - image_style
  - media_type
  - media
  - menu_link_content
  - node
  - node_type
  - path_alias
  - search_page
  - shortcut_set
  - shortcut
  - menu
  - action
  - taxonomy_term
  - taxonomy_vocabulary
  - tour
  - user
  - user_role
  - pathauto_pattern
  - view
  - paragraph
  - paragraphs_type
  - base_field_override
  - entity_form_display
  - entity_form_mode
  - entity_view_mode
  - entity_view_display
  - date_format
  - asset_injector_css
  - asset_injector_js
