_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: 96c16fd5-6790-4184-8edf-ce20fae0242b
name: Drupal
mail: ajay.mallah@innoraft.com
slogan: ''
page:
  403: ''
  404: ''
  front: /home
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: ''
